variables:
  MAVEN_OPTS: "-Xmx4g"
  JAVA_TOOL_OPTIONS: "-Xmx4g"

default:
  image: maven:3.9-eclipse-temurin-21
  before_script:
  - apt-get update && apt-get install -y xvfb libx11-6 libxrender1 libxtst6 libxi6 libgtk-3-0 libglib2.0-0 libgdk-pixbuf2.0-0 libatk1.0-0 libpango-1.0-0 libpangocairo-1.0-0

stages:
- build
- test
- package

maven_build:
  stage: build
  script:
  - mvn compile
  artifacts:
    paths:
    - target/classes/

maven_test:
  stage: test
  script:
  - xvfb-run mvn test -DargLine="-Xmx4g"
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

maven_package:
  stage: package
  script:
  - xvfb-run mvn package -DargLine="-Xmx4g"
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1 week
