default:
  image: maven:3.9-eclipse-temurin-21 # Use a Maven image with a recent LTS JDK

stages:
- build
- test
- package

maven_build:
  stage: build
  script:
  - mvn compile
  artifacts:
    paths:
    - target/classes/ # Optional: if you need compiled classes for other jobs

maven_test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  before_script:
  - apt-get update && apt-get install -y xvfb libx11-6 libxrender1 libxtst6 libxi6 libgtk-3-0 libglib2.0-0 libgdk-pixbuf2.0-0 libatk1.0-0 libpango-1.0-0 libpangocairo-1.0-0
  script:
  - xvfb-run mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

maven_package:
  stage: package
  image: maven:3.9-eclipse-temurin-21
  before_script:
  - apt-get update && apt-get install -y xvfb libx11-6 libxrender1 libxtst6 libxi6 libgtk-3-0 libglib2.0-0 libgdk-pixbuf2.0-0 libatk1.0-0 libpango-1.0-0 libpangocairo-1.0-0
  script:
  - xvfb-run mvn package # This typically creates the JAR
  artifacts:
    paths:
    - target/*.jar # Save the JAR file(s)
    expire_in: 1 week
