stages:
  - test
  - build

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - mvn --version
    - mvn clean test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - mvn clean package -P release
  artifacts:
    paths:
      - target/*.zip
    expire_in: 2 week
