package com.algaecare.model;

public enum GameState {
    TITLE,
    SUBTITLE,
    NOT_AXOLOTL,
    AXOLOTL_INTRODUCTION,
    GAMEPLAY,
    OBJECT_GARBAGE_BAG,
    OBJECT_CAR,
    OBJECT_AIRPLANE,
    OBJECT_SHOPPING_BASKET_INTERNATIONAL,
    OBJECT_RECYCLING_BIN,
    OBJECT_TRAIN,
    OBJECT_SHOPPING_BASKET_LOCAL,
    OBJECT_BICYCLE,
    OBJECT_TRASH_GRABBER,
    ENDSCREEN_NEGATIVE,
    ENDSCREEN_POSITIVE,
    GOODBYE
}